data:
  path: /root/autodl-tmp/CurES/output/gsm8k_generations.parquet  # 对齐项目输出路径
  prompt_key: prompt
  response_key: responses
  data_source_key: data_source
  reward_model_key: reward_model

custom_reward_function:
  path: "/root/working/CurES/verl/utils/reward_score/gsm8k.py"
  name: "compute_score"

ray_init:
  num_cpus: null # `None` means using all CPUs, which might cause hang if limited in systems like SLURM. Please set to a number allowed then.